---
title: "CV"
---

------------------------------------------------------------------------

### Short Bio

I studied Economics and Political Science at the University of Konstanz and Princeton University. Under supervision of Heinz König I completed my dissertation the University of Mannheim in 1989, followed by post-doctoral positions as a John F. Kennedy Fellow at Harvard University (1989/1990) and the University of Mannheim. From 1994 until March 2023 I worked as a professor of Economics and Econometrics at the University of Konstanz. Since September 2024 I hold the position of a Seniorprofessor for Computational Statistics at the the Zeppelin University in Friedrichshafen.

```{=html}
<!--
[Download my CV pdf](https://raw.githubusercontent.com/W-Pohlmeier/WP-Website/main/CV_Pohlmeier_2023_04.pdf)
-->
```

<!-- [Download my CV pdf](https://cloud.uni-konstanz.de/index.php/f/169209253) -->

[Download my CV pdf](https://cloud.uni-konstanz.de/index.php/s/k5YTWzKS2wXaDZR)

### Former PhD students 

-   [Sikandar Siddiqui (1997):](https://www.linkedin.com/in/sikandarsiddiqui/?originalSubdomain=de) The Transition to Retirement , Postdoctoral Researcher (Hochschulassistent), University of Hamburg.

-   [Joachim Inkmann (2000):](https://fbe.unimelb.edu.au/our-people/staff/finance/joachim-inkmann): Conditional Moment Estimation of Nonlinear Equation Systems, Postdoctoral Researcher, London School of Economics

-   [Frank Gerhard (2001)](https://www.linkedin.com/in/frankgerhard/?originalSubdomain=de): Empirical Models of the Intraday Process of Price Changes and Liquidity: An Transaction Level Approach , Postdoctoral Researcher, University of Oxford

-   [Ulrich Kaiser (2001):](https://www.business.uzh.ch/en/research/professorships/entrepreneurship/team/kaiser.html) Innovation, Employment and Firm Performance in the Ger man Service Sector , Postdoctoral Researcher, Harvard University

-   [Nikolaus Hautsch (2003):](https://homepage.univie.ac.at/nikolaus.hautsch/) Modeling Irregular Spaced Financial data: Theory and Practice of Dynamic Duration, and Modelling Intensity Models , Assist. Prof., University of Copenhagen.

-   [Stefan Klotz (2004):](https://www.linkedin.com/in/stefanklotzvif/?originalSubdomain=de) Cross Sectional Dependence in Spatial Econometrics Models , Bankhaus Delbrück

-   [Markus Jochmann (2006):](https://www.linkedin.com/in/markus-jochmann-345b49138/?originalSubdomain=de) Three Essays in Nonparametric Bayesian Microeconometrics, Postdoctoral Researcher, Universite Catholique de Louvain

-   Michael Maier (2008): Three New Semiparametric Econometric Evaluation Methods , Postdoctoral Researcher, University of Mannheim

-   [Sandra Nolte (2008):](https://www.lancaster.ac.uk/lums/people/sandra-nolte) Measurement Error in Nonlinear Models: An Application to Disclosure Limitation Techniques , Postdoctoral Researcher, Warwick Business School

-   [Ingmar Nolte (2008):](https://www.lancaster.ac.uk/lums/people/ingmar-nolte) Three Essays in High Frequency Econometrics and Individual Trading Behavior, Assist. Prof., Warwick Business School

-   [Anton Flossmann (2008):](https://www.linkedin.com/in/dr-anton-flossmann-77b03593) Three Essays on Matching Methods for the Missing Observations Problem , Hypo-Vereinsbank, Munich

-   [Valeri Voev (2008):](https://www.linkedin.com/in/valeri-voev-1a698940/?originalSubdomain=dk%3E) Three Essays on Estimation and Dynamic Modeling of Multivariate Market Risks using High Frequency Financial Data , Assist. Prof., University of Aarhus

-   [Magdalena Ramada-Sarasola (2009):](https://www.linkedin.com/in/magdalena-ramada-sarasola-phd-73560210/?originalSubdomain=es) Four Essays on Firm Offshoring and Innovation Behavior , Assist. Prof. Universidad de la Republica, Montevideo, Uruguay

-   [Roxana Halbleib Chiriac (2010):](https://www.econometrics.uni-freiburg.de/de/mitarbeitende/roxana-halbleib) Four Essay on Measuring Financial Risks, Postdoctoral Researcher, Free University of Brussels

-   [Remi Piatek (2010):](https://www.linkedin.com/in/remi-piatek/?originalSubdomain=dk) Three Essays on Bayesian Factor Models , Postdoctoral Researcher, University of Chicago

-   [Laura Wichert (2010):](https://www.linkedin.com/in/laura-wichert-913345106/?originalSubdomain=de) Three Essays on Empirical Labor Economics, Deutsche Bundesbank

-   [Derya Uysal (2011):](https://www.deryauysal.com/) Three Essays on Double Robust Estimation, Assist. Prof. Institute for Advanced Studies, Vienna

-   [Lidan Großmaß (2013)](https://www.linkedin.com/in/lidan-grossmass-frm-phd-1845b05?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BvGogCPitS9WJh18HRAep3A%3D%3D) Three Essays On Using High Frequency Data in Estimating Financial Risks , Postdoctoral Researcher, University of Düsseldorf

-   [Peter Schanbacher (2013):](https://www.hs-furtwangen.de/personen/profil/2700-peterschanbacher/) Four Essays on Robustiﬁcation of Portfolio Models, Zürich Versicherung

-   [Ruben Seiberlich (2013):](https://www.zhaw.ch/de/ueber-uns/person/seib/) Three Essays on Semiparametric Econometric Evaluation: Methods and Applications, Credit Suisse, Zurich.

-   [Hao Liu (2013):](https://www.linkedin.com/in/hao-l-357b6664?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3Bogsvbdr8RkWXIHyDb1V2VQ%3D%3D) Three Essays on Robust Optimization of Eﬃcient Portfolios, UBS, Zurich.

-   [Frieder Mokinski (2013):](https://www.linkedin.com/in/frieder-mokinski-371103b4?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BKeP4BiBGQCq%2BbUIGId7SfQ%3D%3D) Three Essays on the Econometrics of Survey Expectations Data, Deutsche Bundesbank

-   [Fabian Krüger (2013):](https://ewifo.stat.kit.edu/21_57.php) Four Essays on Probabilistic Forecasting in Econometrics, Postdoctoral Researcher, University of Heidelberg

-   [Christoph Frey (2017):](https://www.linkedin.com/in/christoph-frey-b66a164?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3Bks5li8ZHQ2itrVtC%2FKvQQw%3D%3D) Three Essays on Bayesian Shrinkage Methods, Assistant Prof., Erasmus University Rotterdam.

-   [Sebastian Bayer (2018):](https://www.linkedin.com/in/sebastian-bayer?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3Bx8W1zgeWQNWVG5EJ6Fscew%3D%3D) Three Essays on Improving Financial Risk Estimation,Forecasting and Backtesting, Data Scientist at the Bosch Center for Artiﬁcial Intelligence, Robert Bosch GmbH.

-   [Jana Mareckova (2019):](https://sites.google.com/view/janamareckova) Three Essays on Regularization and Machine Learning, Postdoctoral Researcher, University of St. Gallen.

-   [Ekaterina Kazak (2019):](https://www.birmingham.ac.uk/staff/profiles/business/kazak-ekaterina) Three Essays on Robust Inference in Economics and Finance, Lecturer, University of Manchester.

-   [Aygul Zagidullina (2019):](https://www.linkedin.com/in/aygul-zagidullina-phd-2307?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3B6bmypPjzR3mR%2F%2BwVAz%2FWkQ%3D%3D) Three Essays on Covariance Matrix Estimation and Factor Models in High Dimensions, Data Scientist at Digital Transformations & Products Labs, Credit Suisse, Zurich.

-   [Phillip Heiler (2019):](https://www.au.dk/en/show/person/pheiler@econ.au.dk) Three Essays on Statistical Inference and Estimation for Heterogeneous Causal Eﬀects in Economics, Assistant Prof., University of Aarhus.

-   [Anastasia Simmet (2021):](https://www.linkedin.com/in/anastasia-simmet-413b1894?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3B6G4YoWHxRSuejgQO9UyNxw%3D%3D) Three Essays on Estimation Techniques for Econometric Models with Endogeneity, Data Scientist, YAZIO.

-   [Gerhard Fechteler (2022):](https://www.linkedin.com/in/dr-gerhard-fechteler-87293113b?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BKg76uLY7QSC9Y0BZ1Uu78w%3D%3D) Three Essays on Time Series Analysis and Neural Net- works in Econometrics, Portfolio Manager, Credit Suisse.

-   [Livia Shkoza (2023):](https://www.linkedin.com/in/livia-shkoza?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BD%2FLVbj3aRO%2BUf%2FHcvaxUtg%3D%3D) Three Essays on Social Networks in Economics, Postdoctoral Researcher, University of Konstanz.

```         
....
```
